# conda env create -f conda.yaml
# conda activate btc
name: btc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - pip:
      - python-bitcoinlib
      - python-dotenv